services:
  # Backend API service (connects to Supabase)
  backend:
    image: ghcr.io/bug-bugger/ezmodel-backend:latest
    env_file:
      - .env.prod
    networks:
      - ezmodel-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend service with nginx
  frontend:
    image: ghcr.io/bug-bugger/ezmodel-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - ezmodel-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ezmodel-network:
    driver: bridge