
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ezmodel
      - DB_PASSWORD=ezmodel_password
      - DB_NAME=ezmodel
      - DB_SSLMODE=disable
      - JWT_SECRET=development-secret-change-in-production
      - JWT_ACCESS_TOKEN_EXP=15m
      - JWT_REFRESH_TOKEN_EXP=168h
      - PORT=8080
      - ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ezmodel-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ezmodel
      - POSTGRES_PASSWORD=ezmodel_password
      - POSTGRES_DB=ezmodel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ezmodel -d ezmodel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - ezmodel-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  ezmodel-network:
    driver: bridge